dim=10
board={
    "A":[None]*dim,
    "B":[None]*dim,
    "C":[None]*dim,
    "D":[None]*dim,
    "E":[None]*dim,
    "F":[None]*dim,
    "G":[None]*dim,
    "H":[None]*dim,
    "I":[None]*dim,
    "J":[None]*dim
}
print(board)